---

- name: Set munge key source path
  ansible.builtin.set_fact:
    __slurm_munge_key_path: "{{ slurm_munge_key | default(role_path ~ '/files/munge.key') }}"

- name: Verify that munge.key exists on Deploy Node
  ansible.builtin.stat:
    path: "{{ __slurm_munge_key_path }}"
  delegate_to: localhost
  run_once: true
  become: false
  register: __munge_key_stat
  failed_when: not __munge_key_stat.stat.exists

- name: Check munge dir
  ansible.builtin.file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Install munge key
  ansible.builtin.copy:
    src: "{{ __slurm_munge_key_path }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  notify:
    - Restart munge

- name: Ensure Munge is enabled and running
  ansible.builtin.service:
    name: munge
    enabled: true
    state: started
